plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'Main'
}

group = 'org.SEFB.IBM'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jfree:jfreechart:1.5.5'
    implementation 'com.formdev:flatlaf:3.6.2'
    implementation "com.formdev:flatlaf-extras:3.4"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.intellij:forms_rt:7.0.3'
}

test {
    useJUnitPlatform()
}