plugins {
    id 'java'
}

group = 'org.SEFB.IBM'
version = '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Savitzky-Golat Filtering:
    // https://mvnrepository.com/artifact/io.github.ruozhuochen/savitzky-golay-filter
    implementation 'io.github.ruozhuochen:savitzky-golay-filter:1.0.1'
    implementation 'org.apache.commons:commons-math3:3.6.1'

    implementation platform("org.eclipse.jetty:jetty-bom:12.1.5")
    implementation "org.eclipse.jetty:jetty-server"
    implementation "org.eclipse.jetty.websocket:jetty-websocket-jetty-server"
    implementation "org.eclipse.jetty:jetty-slf4j-impl"
}

tasks.register("runServer", JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = "Main"
}

test {
    //useJUnitPlatform()
    failOnNoDiscoveredTests = false
}