package ibm.gui.design;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;
import java.util.Objects;

public class SetupPage {
    private JPanel panel1;
    private JRadioButton input_one_select;
    private JRadioButton input_two_select;
    private JLabel setup_title;
    private JButton button_finish_setup;
    private JPanel input_number_panel;
    private JPanel numWavePanel;
    private JButton button_loadSetup;
    private JLabel patientNameLabel;
    private JTextField patientNameField;
    private JLabel radioLabel;
    private JLabel sampleLabel;
    private JTextField sampleRateField;
    private JTextField patientID;
    private JLabel patientIdLabel;
    private ButtonGroup input_num_select;

    public JPanel getPanel() {
        return panel1;
    }

    public JButton getButton_finish_setup() {
        return button_finish_setup;
    }

    public JButton getButton_loadSetup() {
        return button_loadSetup;
    }

    public String getPatientName() {
        return patientNameField.getText();
    }

    public int getNumWaveForms() {
        if (input_one_select.isSelected()) return 1;
        if (input_two_select.isSelected()) return 2;
        return 0;
    }

    private void setFonts() {
        Font f = new Font(".AppleSystemUIFont", Font.BOLD, 24);
        setup_title.setFont(f);
        Font f1 = new Font(".AppleSystemUIFont", Font.BOLD, 14);
        patientNameLabel.setFont(f1);
        radioLabel.setFont(f1);
        sampleLabel.setFont(f1);
        patientIdLabel.setFont(f1);
        Font f2 = new Font(".AppleSystemUIFont", Font.BOLD, 16);
        button_finish_setup.setFont(f2);
        button_loadSetup.setFont(f2);
    }

    public void darkenBackground() {
        input_number_panel.setBackground(panel1.getBackground().darker());
        button_loadSetup.setBackground(panel1.getBackground().brighter());
        button_finish_setup.setBackground(UIManager.getColor("Button.default.accent"));
    }

    public int getPatientId() throws SetupValueException {
        try {
            int val = Integer.parseInt(Objects.requireNonNull(patientID.getText()));
            if (Integer.signum(val) == 1) return val;
            else throw new Exception();
        } catch (Exception e) {
            throw new SetupValueException("Patient ID: Enter only Positive Integers.");
        }
    }

    public int getSampleRate() throws SetupValueException {
        try {
            int val = Integer.parseInt(Objects.requireNonNull(sampleRateField.getText()));
            if (Integer.signum(val) == 1) return val;
            else throw new Exception();
        } catch (Exception e) {
            throw new SetupValueException("Sample Rate: Enter only Positive Integers.");
        }
    }

    public SetupPage() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        setFonts();
        darkenBackground();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setOpaque(true);
        panel1.setVisible(true);
        input_number_panel.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(input_number_panel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(527, 42), null, 0, false));
        final Spacer spacer1 = new Spacer();
        input_number_panel.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 15), null, 0, false));
        final Spacer spacer2 = new Spacer();
        input_number_panel.add(spacer2, new GridConstraints(0, 0, 6, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(10, 11), null, 0, false));
        final Spacer spacer3 = new Spacer();
        input_number_panel.add(spacer3, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 15), null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setFocusable(false);
        panel2.setOpaque(false);
        input_number_panel.add(panel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(613, 71), null, 0, false));
        patientNameLabel = new JLabel();
        Font patientNameLabelFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 14, patientNameLabel.getFont());
        if (patientNameLabelFont != null) patientNameLabel.setFont(patientNameLabelFont);
        patientNameLabel.setText("Patient Name");
        panel2.add(patientNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        patientNameField = new JTextField();
        Font patientNameFieldFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.PLAIN, 14, patientNameField.getFont());
        if (patientNameFieldFont != null) patientNameField.setFont(patientNameFieldFont);
        patientNameField.setHorizontalAlignment(0);
        panel2.add(patientNameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(200, 30), 0, false));
        radioLabel = new JLabel();
        Font radioLabelFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 14, radioLabel.getFont());
        if (radioLabelFont != null) radioLabel.setFont(radioLabelFont);
        radioLabel.setText("Select the Number of Pressure Waveforms");
        panel2.add(radioLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numWavePanel = new JPanel();
        numWavePanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        numWavePanel.setOpaque(false);
        panel2.add(numWavePanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
        input_two_select = new JRadioButton();
        input_two_select.setBorderPainted(true);
        Font input_two_selectFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.PLAIN, 12, input_two_select.getFont());
        if (input_two_selectFont != null) input_two_select.setFont(input_two_selectFont);
        input_two_select.setText("Two Input Waveform");
        numWavePanel.add(input_two_select, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        input_one_select = new JRadioButton();
        input_one_select.setBorderPainted(true);
        Font input_one_selectFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.PLAIN, 12, input_one_select.getFont());
        if (input_one_selectFont != null) input_one_select.setFont(input_one_selectFont);
        input_one_select.setSelected(true);
        input_one_select.setText("One Input Wavefrom");
        numWavePanel.add(input_one_select, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sampleLabel = new JLabel();
        Font sampleLabelFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 14, sampleLabel.getFont());
        if (sampleLabelFont != null) sampleLabel.setFont(sampleLabelFont);
        sampleLabel.setText("Device Sample Rate");
        panel2.add(sampleLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sampleRateField = new JTextField();
        sampleRateField.setHorizontalAlignment(0);
        sampleRateField.setToolTipText("Input the recording devices sample rate");
        panel2.add(sampleRateField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(200, 30), 0, false));
        patientID = new JTextField();
        patientID.setHorizontalAlignment(0);
        patientID.setToolTipText("Input the patient's ID");
        panel2.add(patientID, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(200, 30), 0, false));
        patientIdLabel = new JLabel();
        Font patientIdLabelFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 14, patientIdLabel.getFont());
        if (patientIdLabelFont != null) patientIdLabel.setFont(patientIdLabelFont);
        patientIdLabel.setText("Patient ID");
        panel2.add(patientIdLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setOpaque(false);
        input_number_panel.add(panel3, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        button_loadSetup = new JButton();
        button_loadSetup.setAutoscrolls(false);
        button_loadSetup.setBackground(new Color(-13947600));
        button_loadSetup.setBorderPainted(true);
        Font button_loadSetupFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 16, button_loadSetup.getFont());
        if (button_loadSetupFont != null) button_loadSetup.setFont(button_loadSetupFont);
        button_loadSetup.setText("Load File");
        panel3.add(button_loadSetup, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 40), new Dimension(120, 40), new Dimension(-1, 40), 0, false));
        button_finish_setup = new JButton();
        button_finish_setup.setAutoscrolls(false);
        button_finish_setup.setBackground(new Color(-16722079));
        button_finish_setup.setBorderPainted(true);
        Font button_finish_setupFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 16, button_finish_setup.getFont());
        if (button_finish_setupFont != null) button_finish_setup.setFont(button_finish_setupFont);
        button_finish_setup.setText("Finish Setup");
        panel3.add(button_finish_setup, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 40), new Dimension(288, 40), new Dimension(-1, 40), 0, false));
        final Spacer spacer4 = new Spacer();
        input_number_panel.add(spacer4, new GridConstraints(1, 2, 5, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(15, -1), null, 0, false));
        final Spacer spacer5 = new Spacer();
        input_number_panel.add(spacer5, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer6 = new Spacer();
        panel1.add(spacer6, new GridConstraints(0, 0, 4, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(50, 11), null, 0, false));
        final Spacer spacer7 = new Spacer();
        panel1.add(spacer7, new GridConstraints(0, 2, 5, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(50, -1), new Dimension(50, -1), 0, false));
        final Spacer spacer8 = new Spacer();
        panel1.add(spacer8, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer9 = new Spacer();
        panel1.add(spacer9, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 5), null, 0, false));
        setup_title = new JLabel();
        Font setup_titleFont = this.$$$getFont$$$(".AppleSystemUIFont", Font.BOLD, 24, setup_title.getFont());
        if (setup_titleFont != null) setup_title.setFont(setup_titleFont);
        setup_title.setText("Setup");
        panel1.add(setup_title, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer10 = new Spacer();
        panel1.add(spacer10, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 50), null, null, 0, false));
        input_num_select = new ButtonGroup();
        input_num_select.add(input_one_select);
        input_num_select.add(input_two_select);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        this.input_number_panel = new RoundedPanel(20, 2);
    }
}
