package ibm.gui.design;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class MonitorPage {
    private JPanel panel1;
    private JSplitPane graphsPane;
    private JScrollPane arterialReservoirPlot;
    private JScrollPane bloodPressurePlot;
    private JPanel control_pane;
    private JPanel graphs_pane;
    private JPanel arppCont;
    private JPanel bppCont;
    private JTabbedPane tabbedPane1;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private double t = 0;
    private int sampleRate = 2048;

    private boolean validSampleRate(double x) {
        if (x == 2) return true;
        else if (x % 2 == 0) {
            return validSampleRate(x / 2);
        } else return false;
    }

    public void setSampleRate(int sampleRate) throws SetupValueException {
        try {
            if (!validSampleRate(sampleRate)) throw new SetupValueException("Sample Rate incorrect: Make base 2");
            this.sampleRate = sampleRate;
        } catch (SetupValueException e) {
            System.out.println(e.getMessage());
        }
    }

    public JPanel getPanel() {
        return panel1;
    }

    public JSplitPane getGraphsPane() {
        return graphsPane;
    }

    public void addSamplePE(double sampleValue) {

    }

    private void darkerZones() {
        graphsPane.setBackground(graphsPane.getBackground().darker());
        bppCont.setBackground(bppCont.getBackground().darker());
        arppCont.setBackground(arppCont.getBackground().darker());
    }

    public MonitorPage() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        darkerZones();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        graphsPane = new JSplitPane();
        graphsPane.setContinuousLayout(true);
        graphsPane.setDividerLocation(265);
        graphsPane.setDividerSize(4);
        graphsPane.setName("Both Graphs");
        graphsPane.setOrientation(1);
        tabbedPane1.addTab("Both Charts", graphsPane);
        arppCont = new JPanel();
        arppCont.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        graphsPane.setLeftComponent(arppCont);
        final JLabel label1 = new JLabel();
        label1.setText("Arterial Reservoir Pressure Plot");
        label1.setVerticalTextPosition(1);
        arppCont.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bppCont = new JPanel();
        bppCont.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        graphsPane.setRightComponent(bppCont);
        final JLabel label2 = new JLabel();
        label2.setText("Blood Pressure Plot");
        label2.setVerticalTextPosition(1);
        bppCont.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Reservoir Pressure Chart", panel2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Blood Pressure Chart", panel3);
        final JToolBar toolBar1 = new JToolBar();
        panel1.add(toolBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        button1 = new JButton();
        button1.setText("Button");
        toolBar1.add(button1);
        button2 = new JButton();
        button2.setText("Button");
        toolBar1.add(button2);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        toolBar1.add(toolBar$Separator1);
        button3 = new JButton();
        button3.setText("Button");
        toolBar1.add(button3);
        button4 = new JButton();
        button4.setText("Button");
        toolBar1.add(button4);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {

    }
}
