server.port=8888

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:8888/pwdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pwdb}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pwdb}
spring.datasource.hikari.maximum-pool-size=5
