server.port=${PORT:8888}

spring.datasource.url=jdbc:postgresql://${PGHOST:${DB_HOST}}:${PGPORT:${DB_PORT}}/${PGDATABASE:${DB_NAME}}
spring.datasource.username=${PGUSER:${DB_USER}}
spring.datasource.password=${PGPASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

